title: "Marcel C."
author: "Marcel C."
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: True             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Homepage, sidebaricon: home}
  - {file: "README.md", title: About me, sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:marceljeanchampagne@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/marceljc3"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/marcel-champagne/"}
  - {title: My website (work in progress), icon: globe, url: ""}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
